version: '3.4'

services:
  recruitingapi:
    image: ${DOCKER_REGISTRY-}recruitingapi
    build:
      context: .
      dockerfile: RecruitingAPI/Dockerfile

  interviewapi:
    image: ${DOCKER_REGISTRY-}interviewapi
    build:
      context: .
      dockerfile: InterviewAPI/Dockerfile

